spring；
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev      #开发环境
  application: 
    name: microservicecloud-config-guigu-dev  

---
spring:
  profiles: test      #开发环境
  application: 
    name: microservicecloud-config-guigu-test

